### ISSUE TITLE
Plugin is not defined on MapControl.setup - browser launch

### ISSUE THREAD

**Issue by ouya99** [gwendall/meteor-google-maps-cordova#2]
Calling MapControl.setup("cordovaMap", mapOptions);

results in
ReferenceError: plugin is not defined
from api.js:6

....
    var map = plugin.google.maps.Map.getMap(container, options);
....

**Comment by gwendall** [comment]
Did you call it before Meteor.startup, or your template rendered? If yes this is normal, the plugin var is not available yet.

**Comment by ouya99** [comment]
I did call it from within startup. see below.
 As the meteor-guide says. all DOM should be available by then.

  Meteor.startup(function () {
    var mapOptions = {
      'backgroundColor': 'white'
    };
    MapControl.setup("cordovaMap", mapOptions);
  });

**Comment by gwendall** [comment]
I will dig into that. By the way, the first parameter has to be a DOM node. 
For example with jQuery: `MapControl.setup($('#map').get(0), mapOptions);`

**Comment by gwendall** [comment]
Oh, are you trying to run it from the browser? If yes this is normal. You have to run it from Cordova. Docs here: https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration.

I will make sure to return an appropriate error message if this package is run from the browser.

**Comment by ouya99** [comment]
Thats it. I was running it from the browser.

Now I was trying to build for android and ran into a plugin problem, where the download is stuck at 38%

 meteor run android-device

=> Started proxy.  
=> Started MongoDB.  
   Installing Cordova plugins                [==========               ] 38% 258.1s

so...
meteor remove gwendall:google-maps-cordova

and the build is running fine. Could this be due to your update to 0.1.4?

**Comment by gwendall** [comment]
It is getting the cordova package from its tarball on github so it takes about 5-10 mns to get. No work around.

**Comment by ouya99** [comment]
While adding plugin https://github.com/wf9a5m75/phonegap-googlemaps-plugin.git#e77d0edc6e561c74dc9ce755f93ee5295e74185f to Cordova project:
   Cordova error: Failed to fetch plugin https://github.com/wf9a5m75/phonegap-googlemaps-plugin.git via git.
   Either there is a connection problems, or plugin spec is incorrect:
   Error: git: Command failed with exit code 128 Error output:
   Cloning into '/var/folders/pm/c9jbj_3s2zjfvk5rjk7byxgw0000gn/T/git/1445069083673'...
   error: RPC failed; result=18, HTTP code = 200
   fatal: The remote end hung up unexpectedly
   fatal: early EOF
   fatal: index-pack failed
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to help diagnose the issue.)

will try again later..... maybe I will try a complete cache clear, reset etc...

**Comment by ouya99** [comment]
Oh it was not about the tarball

   While adding plugin https://github.com/wf9a5m75/phonegap-googlemaps-plugin.git#e77d0edc6e561c74dc9ce755f93ee5295e74185f to Cordova project:
   Error: Variable(s) missing: API_KEY_FOR_ANDROID 

So now after about 5min on 38% it says API key is missing. Where would I have to put the key?

**Comment by gwendall** [comment]
In mobile-config.js:

```
App.configurePlugin('plugin.google.maps', {
  'API_KEY_FOR_ANDROID': YOUR_ANDROID_KEY,
  'API_KEY_FOR_IOS': YOUR_IOS_KEY
});
```

**Comment by java99** [comment]
Inside a html file I have a meteor template holding a div named cordovaMap

<div id="cordovaMap" class="map-container">
 </div>

then I have JS-code in a seperate file calling

**Comment by ouya99** [comment]
Inside a html file I have a meteor template holding a div with the id "cordovaMap"

then I have JS-code in a seperate file calling the map:

if (Meteor.isCordova) {
  Meteor.startup(function () {

```
var mapOptions = {
  'backgroundColor': 'white'
};
MapControl.setup($('cordovaMap').get(0), mapOptions);
```

  });
}

yet it does not get it displayed... Also tried with '$('#cordovaMap').get(0)'. 

Is Jquery notation supported here? (standard meteor project?).

**Comment by gwendall** [comment]
It is. You have to make sure you div is rendered before calling this function. If it is in a template, call the function within the Template.foo.onRendered instead of Meteor.startup.

**Comment by gwendall** [comment]
Besides $('#cordovaMap').get(0) is the correct object.

**Comment by ouya99** [comment]
Great got it. Just as u said!

**Comment by ouya99** [comment]
Now I just need some more functions (markers, zoom). I assume to just grab them from what is defined in api.js, right?
